# # k8s/ingress.yaml
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nextjs-app-ingress
#   annotations:
#     kubernetes.io/ingress.class: 'nginx'
#     nginx.ingress.kubernetes.io/ssl-redirect: 'false'
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: nextjs-app
#                 port:
#                   number: 80

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-app-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  rules:
    - host: ${INGRESS_IP}
      http:
        paths:
          - path: /dev
            pathType: Prefix
            backend:
              service:
                name: nextjs-app-dev
                port:
                  number: 80
          - path: /prod
            pathType: Prefix
            backend:
              service:
                name: nextjs-app-prod
                port:
                  number: 80
